package agent

import (
	"context"
	"encoding/json"
	"fmt"
	"regexp"
	"strconv"
	"strings"

	"spore/githubclient"
	"spore/sandbox"
)

type StepError struct {
	Step int
	Err  error
}

func (e *StepError) Error() string {
	return fmt.Sprintf("Failed at step %d: %v", e.Step, e.Err)
}

func fail(step int, err error) error {
	return &StepError{Step: step, Err: err}
}

func issueURL(msg string) (string, int, bool) {
	re := regexp.MustCompile(`https://github\.com/([^/\s]+/[^/\s]+)/issues/([0-9]+)`)
	match := re.FindStringSubmatch(msg)
	if len(match) == 0 {
		return "", 0, false
	}
	number, err := strconv.Atoi(match[2])
	return match[1], number, err == nil
}

func (a *Agent) openPR(ctx context.Context, repo, branch string, issue int, title string) (string, error) {
	base, err := a.github.DefaultBranch(ctx, repo)
	if err != nil || base == "" {
		base = "main"
	}
	return a.github.CreatePR(ctx, githubclient.PRRequest{
		Repo: repo, Title: "fix: " + title,
		Body: fmt.Sprintf("Closes #%d\n\nAutomatically generated by Slack Agent.", issue),
		Head: branch, Base: base,
	})
}

func (a *Agent) codexJSON(sb *sandbox.Sandbox, prompt string, target any) error {
	var last error
	for attempt := 0; attempt < 2; attempt++ {
		text, err := sb.RunCodex("/home/user", a.codexModel, prompt)
		if err != nil {
			return err
		}
		if last = json.Unmarshal([]byte(extractJSON(text)), target); last == nil {
			return nil
		}
	}
	return fmt.Errorf("Codex returned malformed JSON: %w", last)
}

// extractJSON peels markdown code fences and surrounding prose off a model
// response, returning the JSON object inside.
func extractJSON(text string) string {
	text = strings.TrimSpace(text)
	if start := strings.Index(text, "{"); start >= 0 {
		if end := strings.LastIndex(text, "}"); end > start {
			return text[start : end+1]
		}
	}
	return text
}

func slug(s string) string {
	s = regexp.MustCompile(`[^a-zA-Z0-9]+`).ReplaceAllString(strings.ToLower(s), "-")
	s = strings.Trim(s, "-")
	if len(s) > 48 {
		s = strings.Trim(s[:48], "-")
	}
	if s == "" {
		return "issue"
	}
	return s
}
